properties:
  - name: "property1"
    type: "home"
    inputs:
      - id: "value_growth"
        type: "numericInput"
        label: "Home Property Year-on-Year value Growth (% per year)"
        value: 5.00
        description: "Annual growth rate of the investment property value"
      - id: "value_today"
        type: "numericInput"
        label: "Home property price today (EUR)"
        value: 500000
        description: "Current market value of the property"
      - id: "purchase_year"
        type: "numericInput"
        label: "Year property purchase"
        value: 2030
        description: "Year when the property will be purchased"
      - id: "sale_year"
        type: "numericInput"
        label: "Year property sold"
        value: 2045
        description: "Year when the property will be sold"
      - id: "initial_interest_rate"
        type: "numericInput"
        label: "Interest rate on mortgage (% per year)"
        value: 3.70
        description: "Interest rate for the mortgage"
      - id: "principal_repayment_rate"
        type: "numericInput"
        label: "Principal repayment rate (% per year)"
        value: 2.00
        description: "Annual rate of mortgage principal repayment (Rückzahlungsrate)."
      - id: "max_mortgage_amortization_rate"
        type: "numericInput"
        label: "Maximal mortgage principal amortization rate (% per year)"
        value: 5.00
        description: "Maximal annual rate of amortization allowed by your mortgage contract for the principal. This is the maximum value (Percent of principal) your mortgage contract with the bank will allow you to pay in extra installments every year to speed-up the payment of your mortgage."

      - id: "loan_family_friends"
        type: "numericInput"
        label: "Loan from family/friends (EUR)"
        value: 0
        description: "Amount borrowed from family or friends"
      - id: "interest_rate_family_friends"
        type: "numericInput"
        label: "Interest rate on loan from family/friends (% per year)"
        value: 3.70
        description: "Interest rate for family/friends loan"
      - id: "duration_payback_family_friends"
        type: "numericInput"
        label: "Duration payback family/friends loan (years)"
        value: 10
        description: "Duration to pay back family/friends loan"

      - id: "property_taxes_rate"
        type: "numericInput"
        label: "Property taxes rate (% property value per year)"
        value: 0.30
        description: "Annual property tax rate"
      - id: "maintenance_cost_rate"
        type: "numericInput"
        label: "Maintenance cost rate (% property value per year)"
        value: 0.75
        description: "Annual maintenance cost as a percentage of property value"
      - id: "hausgeld_fees_total"
        type: "numericInput"
        label: "Hausgeld (EUR/month)"
        value: 330
        description: "Monthly Hausgeld fees total. Sum of all other Hausgeld fees and costs: Building maintenance, utilities, reserve fund contributions, property management fees, building insurance, etc."
      - id: "hausgeld_maintenance_costs"
        type: "numericInput"
        label: "Hausgeld - Building maintenance (EUR/month)"
        value: 75
        description: "Monthly Hausgeld building maintenance costs."
      - id: "hausgeld_utilities"
        type: "numericInput"
        label: "Hausgeld - Utilities (EUR/month)"
        value: 125
        description: "Monthly Hausgeld utilities costs."
      - id: "hausgeld_reserve_fund"
        type: "numericInput"
        label: "Hausgeld - Reserve fund contributions (EUR/month)"
        value: 40
        description: "Monthly Hausgeld reserve fund contributions."
      - id: "hausgeld_house_management_fee"
        type: "numericInput"
        label: "Hausgeld - Property management fee (EUR/month)"
        value: 40
        description: "Monthly Hausgeld property management fee."
      - id: "hausgeld_building_insurance"
        type: "numericInput"
        label: "Hausgeld - Building insurance (EUR/month)"
        value: 50
        description: "Monthly Hausgeld building insurance cost."

  - name: "property2"
    type: "investment"
    inputs:
      - id: "value_growth"
        type: "numericInput"
        label: "Investment Property Year-on-Year value Growth (% per year)"
        value: 5.00
        description: "Annual growth rate of the investment property value"
      - id: "value_today"
        type: "numericInput"
        label: "Property price today (EUR)"
        value: 415000
        description: "Current market value of the property."
      - id: "purchase_year"
        type: "numericInput"
        label: "Year property purchase"
        value: 2055
        description: "Year when the property will be purchased."
      - id: "sale_year"
        type: "numericInput"
        label: "Year property sold"
        value: 2060
        description: "Year when the property will be sold."
      - id: "initial_interest_rate"
        type: "numericInput"
        label: "Interest rate on mortgage (% per year)"
        value: 3.70
        description: "Interest rate for the mortgage"
      - id: "principal_repayment_rate"
        type: "numericInput"
        label: "Principal repayment rate (% per year)"
        value: 2.00
        description: "Annual rate of mortgage principal repayment (Rückzahlungsrate)"
      - id: "max_mortgage_amortization_rate"
        type: "numericInput"
        label: "Maximal mortgage principal amortization rate (% per year)"
        value: 5.00
        description: "Maximal annual rate of amortization allowed by your mortgage contract for the principal. This is the maximum value (Percent of principal) your mortgage contract with the bank will allow you to pay in extra installments every year to speed-up the payment of your mortgage."

      - id: "loan_family_friends"
        type: "numericInput"
        label: "Loan from family/friends (EUR)"
        value: 0
        description: "Amount borrowed from family or friends"
      - id: "interest_rate_family_friends"
        type: "numericInput"
        label: "Interest rate on loan from family/friends (% per year)"
        value: 3.70
        description: "Interest rate for family/friends loan"
      - id: "duration_payback_family_friends"
        type: "numericInput"
        label: "Duration payback family/friends loan (years)"
        value: 10
        description: "Duration to pay back family/friends loan"


      - id: "cold_lease_today"
        type: "numericInput"
        label: "Cold lease today (EUR/month)"
        value: 1155
        description: "Current monthly cold lease amount"
      - id: "lease_rental_growth"
        type: "numericInput"
        label: "Lease rental prices growth (% per year)"
        value: 5.00
        description: "Annual growth rate of lease rental prices"
      - id: "yearly_depreciation_rate"
        type: "numericInput"
        label: "Depreciation (AfA) (% per year)"
        value: 2.00
        description: "Annual depreciation rate of a property's price when purchased. Used for taxes deduction calculation."
      - id: "vacancy_months"
        type: "numericInput"
        label: "Vacancy costs (number of vacant month per year)"
        value: 1.00
        description: "Number of months per year the property is expected to be vacant"
      - id: "property_management_rate"
        type: "numericInput"
        label: "Property Management Fees (% of cold rent)"
        value: 7.50
        description: "Property management fees as a percentage of annual rent"
      - id: "property_taxes_rate"
        type: "numericInput"
        label: "Property taxes rate (% property value per year)"
        value: 0.30
        description: "Annual property tax rate"
      - id: "maintenance_cost_rate"
        type: "numericInput"
        label: "Maintenance cost rate (% property value per year)"
        value: 0.75
        description: "Annual maintenance cost as a percentage of property value"
      - id: "hausgeld_fees_total"
        type: "numericInput"
        label: "Hausgeld (EUR/month)"
        value: 330
        description: "Monthly Hausgeld fees total. Sum of all other Hausgeld fees and costs: Building maintenance, utilities, reserve fund contributions, property management fees, building insurance, etc."
      - id: "hausgeld_maintenance_costs"
        type: "numericInput"
        label: "Hausgeld - Building maintenance (EUR/month)"
        value: 75
        description: "Monthly Hausgeld building maintenance costs."
      - id: "hausgeld_utilities"
        type: "numericInput"
        label: "Hausgeld - Utilities (EUR/month)"
        value: 125
        description: "Monthly Hausgeld utilities costs."
      - id: "hausgeld_reserve_fund"
        type: "numericInput"
        label: "Hausgeld - Reserve fund contributions (EUR/month)"
        value: 40
        description: "Monthly Hausgeld reserve fund contributions."
      - id: "hausgeld_house_management_fee"
        type: "numericInput"
        label: "Hausgeld - Property management fee (EUR/month)"
        value: 40
        description: "Monthly Hausgeld property management fee."
      - id: "hausgeld_building_insurance"
        type: "numericInput"
        label: "Hausgeld - Building insurance (EUR/month)"
        value: 50
        description: "Monthly Hausgeld building insurance cost."
